"""Pydantic schemas used across tools, providers, and analysis."""

from __future__ import annotations

from datetime import date, datetime
from typing import Any, Literal

from pydantic import BaseModel, Field, model_validator


Timeframe = Literal["intraday", "swing", "longterm"]
RiskProfile = Literal["conservative", "moderate", "aggressive"]
OutputFormat = Literal["signal", "report"]
TickerType = Literal["stock", "etf", "crypto"]
SignalType = Literal["Buy", "Hold", "Sell"]


class ToolError(BaseModel):
    """Standardized tool error shape."""

    code: str
    message: str
    details: dict[str, Any] = Field(default_factory=dict)


class PriceData(BaseModel):
    """Normalized latest price data."""

    ticker: str
    price: float | None = None
    currency: str | None = None
    timestamp: datetime | None = None
    source: str


class OHLCVBar(BaseModel):
    """Normalized OHLCV row."""

    date: date
    open: float
    high: float
    low: float
    close: float
    volume: float


class TechnicalsData(BaseModel):
    """Calculated technical indicators."""

    rsi: float | None = None
    macd: float | None = None
    macd_signal: float | None = None
    ema_20: float | None = None
    ema_50: float | None = None
    ema_200: float | None = None
    source: str


class FundamentalsData(BaseModel):
    """Normalized fundamentals used by metrics/scoring."""

    ticker: str
    pe: float | None = None
    forward_pe: float | None = None
    ps: float | None = None
    ev_ebitda: float | None = None
    beta: float | None = None
    roe: float | None = None
    debt_to_equity: float | None = None
    gross_margin: float | None = None
    operating_margin: float | None = None
    net_margin: float | None = None
    revenue_yoy: float | None = None
    eps_yoy: float | None = None
    forward_eps_growth: float | None = None
    revenue_history: list[float] = Field(default_factory=list)
    source: str


class NewsSentimentItem(BaseModel):
    """News entry with sentiment score."""

    headline: str
    summary: str | None = None
    sentiment_score: float | None = None
    source: str
    published_at: datetime | None = None


class NewsSentimentData(BaseModel):
    """Normalized sentiment response."""

    ticker: str
    average_sentiment: float | None = None
    articles: list[NewsSentimentItem] = Field(default_factory=list)
    source: str


class MetricsTable(BaseModel):
    """Computed metrics for report generation."""

    revenue_yoy: float | None = None
    revenue_cagr_3y: float | None = None
    revenue_cagr_5y: float | None = None
    eps_yoy: float | None = None
    forward_eps_growth: float | None = None
    margin_trend: float | None = None
    gross_margin: float | None = None
    operating_margin: float | None = None
    net_margin: float | None = None
    roe: float | None = None
    roic: float | None = None
    debt_equity: float | None = None
    pe: float | None = None
    forward_pe: float | None = None
    ps: float | None = None
    ev_ebitda: float | None = None
    beta: float | None = None
    volatility_proxy: float | None = None
    drawdown_risk: float | None = None


class Scorecard(BaseModel):
    """Deterministic stock scores."""

    value: float
    growth: float
    quality: float
    momentum: float
    risk: float
    composite: float


class ResearchRequest(BaseModel):
    """Input payload for primary stock research tool."""

    ticker: str
    comparison_ticker: str | None = None
    timeframe: Timeframe = "swing"
    risk_profile: RiskProfile = "moderate"
    output_format: OutputFormat = "report"

    @model_validator(mode="after")
    def normalize_tickers(self) -> "ResearchRequest":
        """Normalize ticker symbols to uppercase."""

        self.ticker = self.ticker.upper().strip()
        if self.comparison_ticker:
            self.comparison_ticker = self.comparison_ticker.upper().strip()
        return self


class AnalysisSections(BaseModel):
    """Structured narrative sections generated by Claude."""

    executive_summary: str
    growth_analysis: str
    valuation_analysis: str
    risk_assessment: str
    competitive_positioning: str
    final_investment_view: str
    confidence: float = Field(ge=0, le=100)
    key_drivers: list[str]
    bear_case: str
    bull_case: str
    assumptions: list[str] = Field(default_factory=list)


class StockResearchResult(BaseModel):
    """Primary tool output schema."""

    executive_summary: str
    metrics_table: MetricsTable
    scorecard: Scorecard
    growth_analysis: str
    valuation_analysis: str
    risk_assessment: str
    peer_comparison: str
    final_investment_view: str
    confidence: float = Field(ge=0, le=100)
    assumptions: list[str] = Field(default_factory=list)
    signal_if_requested: SignalType | None = None
    disclaimer: str = "Educational use only. Not financial advice."


